apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: astaire
spec:
  replicas: 3
  template:
    metadata:
      labels:
        service: astaire
    spec:
      containers:
      - image: "<MY_REPO>/astaire:latest"
        name: astaire
        ports:
        - containerPort: 22
        - containerPort: 11211
        - containerPort: 11311
        env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        livenessProbe:
          tcpSocket:
            port: 11311
          initialDelaySeconds: 30
        readinessProbe:
          tcpSocket:
            port: 11311
      restartPolicy: Always
