apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: etcd
spec:
  replicas: 3
  template:
    metadata:
      creationTimestamp: null
      labels:
        instance-type: etcd-pod
    spec:
      containers:
      - args:
        - --name
        - $(MY_POD_NAME)
        - --advertise-client-urls
        - http://$(MY_POD_IP):2379,http://$(MY_POD_IP):4001
        - --listen-client-urls
        - http://0.0.0.0:2379,http://0.0.0.0:4001
        - --initial-advertise-peer-urls
        - http://$(MY_POD_IP):2380
        - --listen-peer-urls
        - http://0.0.0.0:2380
        # Discovery using DNS
        #- --discovery-srv
        #- default.svc.cluster.local
        #- --initial-cluster-state
        #- new
        # Using central discvovery:
        - --discovery
        - http://discovery.etcd.io/401ccd1143f1a06cf105840dbc3a4e36
        # Could also have these instead of --discovery (but only for one pod cluster)
        #- --initial-cluster
        #- $(MY_POD_NAME)=http://$(MY_POD_IP):2380
        #- --initial-cluster-state
        #- new
        env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: quay.io/coreos/etcd:v2.2.5
        name: etcd
        ports:
        - containerPort: 2379
        - containerPort: 2380
        - containerPort: 4001
        livenessProbe:
          tcpSocket:
            port: 4001
          initialDelaySeconds: 300
        readinessProbe:
          tcpSocket:
            port: 4001
      restartPolicy: Always
