apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: homestead
spec:
  replicas: 1
  selector:
    matchLabels:
      service: homestead
  template:
    metadata:
      labels:
        service: homestead
        snmp: enabled
    spec:
      containers:
      - image: "{{REPO}}/clearwater/homestead:latest"
        name: homestead
        ports:
        - containerPort: 22
        - containerPort: 8888
        env:
        - name: ZONE
          value: {{ZONE}}
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        livenessProbe:
          exec:
            command: ["/bin/bash", "/usr/share/kubernetes/liveness.sh", "8888"]
          initialDelaySeconds: 60
        readinessProbe:
          exec:
            command: ["/bin/bash", "/usr/share/kubernetes/liveness.sh", "8888"]
        volumeMounts:
        - name: homesteadlogs
          mountPath: /var/log/homestead
      - image: busybox
        name: tailer
        command: [ "tail", "-F", "/var/log/homestead/homestead_current.txt" ]
        volumeMounts:
        - name: homesteadlogs
          mountPath: /var/log/homestead
      volumes:
      - name: homesteadlogs
        emptyDir: {}
      restartPolicy: Always
